
import type { Stock, BacktestEntry } from './types';

const today = new Date().toISOString().split('T')[0];

export const mockStocks: Stock[] = [
  {
    rank: 1,
    ticker: 'NVDA',
    name: 'NVIDIA Corp',
    predicted_multiplier: 3.5,
    confidence: 0.92,
    time_horizon_days: 365,
    key_drivers: ['AI Chip Dominance', 'Strong Earnings Growth', 'Data Center Expansion'],
    risk_flags: ['High Valuation', 'Geopolitical Tensions'],
    risk_level: 'Medium',
    market: 'NASDAQ',
    sector: 'Technology',
    last_updated: today,
  },
  {
    rank: 2,
    ticker: 'TSLA',
    name: 'Tesla, Inc.',
    predicted_multiplier: 2.8,
    confidence: 0.85,
    time_horizon_days: 540,
    key_drivers: ['EV Market Leadership', 'Autonomous Driving Tech', 'Energy Storage Growth'],
    risk_flags: ['Production Scalability', 'Regulatory Scrutiny'],
    risk_level: 'High',
    market: 'NASDAQ',
    sector: 'Consumer Cyclical',
    last_updated: today,
  },
  {
    rank: 3,
    ticker: 'CRWD',
    name: 'CrowdStrike Holdings',
    predicted_multiplier: 4.1,
    confidence: 0.88,
    time_horizon_days: 730,
    key_drivers: ['Leader in Endpoint Security', 'Strong Subscription Growth', 'Expanding TAM'],
    risk_flags: ['High Competition in Cybersecurity', 'Valuation Concerns'],
    risk_level: 'Medium',
    market: 'NASDAQ',
    sector: 'Technology',
    last_updated: today,
  },
  {
    rank: 4,
    ticker: 'PLTR',
    name: 'Palantir Technologies',
    predicted_multiplier: 3.2,
    confidence: 0.81,
    time_horizon_days: 365,
    key_drivers: ['Government Contracts', 'Commercial Expansion (AIP)', 'Unique Data Platform'],
    risk_flags: ['Contract Dependency', 'Negative Sentiment'],
    risk_level: 'High',
    market: 'NYSE',
    sector: 'Technology',
    last_updated: today,
  },
  {
    rank: 5,
    ticker: 'SNOW',
    name: 'Snowflake Inc.',
    predicted_multiplier: 2.5,
    confidence: 0.9,
    time_horizon_days: 540,
    key_drivers: ['Cloud Data Platform Leader', 'High Net Revenue Retention', 'Usage-Based Model'],
    risk_flags: ['Intense Competition', 'High Stock-Based Compensation'],
    risk_level: 'Medium',
    market: 'NYSE',
    sector: 'Technology',
    last_updated: today,
  },
  {
    rank: 6,
    ticker: 'U',
    name: 'Unity Software Inc.',
    predicted_multiplier: 5.2,
    confidence: 0.75,
    time_horizon_days: 730,
    key_drivers: ['Dominant Gaming Engine', 'Expansion into non-gaming industries', 'New Pricing Model Adoption'],
    risk_flags: ['Recent Controversies', 'Dependence on Gaming Market'],
    risk_level: 'High',
    market: 'NYSE',
    sector: 'Technology',
    last_updated: today,
  },
  {
    rank: 7,
    ticker: 'AMD',
    name: 'Advanced Micro Devices',
    predicted_multiplier: 2.9,
    confidence: 0.89,
    time_horizon_days: 365,
    key_drivers: ['Competitive CPU/GPU products', 'Data Center Market Share Gains', 'Xilinx Acquisition Synergy'],
    risk_flags: ['Cyclical Semiconductor Industry', 'Supply Chain Risks'],
    risk_level: 'Medium',
    market: 'NASDAQ',
    sector: 'Technology',
    last_updated: today,
  },
  {
    rank: 8,
    ticker: 'SHOP',
    name: 'Shopify Inc.',
    predicted_multiplier: 3,
    confidence: 0.83,
    time_horizon_days: 540,
    key_drivers: ['E-commerce Platform Growth', 'Merchant Solutions Expansion', 'International Markets'],
    risk_flags: ['Competition from Amazon', 'Slowing E-commerce Growth Post-Pandemic'],
    risk_level: 'Medium',
    market: 'NYSE',
    sector: 'Technology',
    last_updated: today,
  },
  {
    rank: 9,
    ticker: 'RBLX',
    name: 'Roblox Corp',
    predicted_multiplier: 4.5,
    confidence: 0.78,
    time_horizon_days: 730,
    key_drivers: ['Growing User Base (Gen Z)', 'Metaverse Platform Potential', 'Creator Economy'],
    risk_flags: ['Monetization Challenges', 'Content Moderation Risks'],
    risk_level: 'High',
    market: 'NYSE',
    sector: 'Communication Services',
    last_updated: today,
  },
  {
    rank: 10,
    ticker: 'ABNB',
    name: 'Airbnb, Inc.',
    predicted_multiplier: 2.2,
    confidence: 0.86,
    time_horizon_days: 365,
    key_drivers: ['Travel Industry Rebound', 'Flexible Work Trends', 'Strong Brand Recognition'],
    risk_flags: ['Regulatory Hurdles', 'Economic Downturn Impacting Travel'],
    risk_level: 'Medium',
    market: 'NASDAQ',
    sector: 'Consumer Cyclical',
    last_updated: today,
  },
  {
    rank: 11,
    ticker: 'DDOG',
    name: 'Datadog, Inc.',
    predicted_multiplier: 3.8,
    confidence: 0.87,
    time_horizon_days: 730,
    key_drivers: ['Cloud Monitoring Leader', 'Product Diversification', 'Strong Enterprise Adoption'],
    risk_flags: ['High Valuation', 'Competitive Market'],
    risk_level: 'Medium',
    market: 'NASDAQ',
    sector: 'Technology',
    last_updated: today,
  },
  {
    rank: 12,
    ticker: 'MDB',
    name: 'MongoDB, Inc.',
    predicted_multiplier: 3.1,
    confidence: 0.84,
    time_horizon_days: 540,
    key_drivers: ['Leading NoSQL Database', 'Atlas (DBaaS) Growth', 'Developer Popularity'],
    risk_flags: ['Competition from Cloud Providers', 'Open Source Licensing Risks'],
    risk_level: 'Medium',
    market: 'NASDAQ',
    sector: 'Technology',
    last_updated: today,
  },
  {
    rank: 13,
    ticker: 'NET',
    name: 'Cloudflare, Inc.',
    predicted_multiplier: 3.3,
    confidence: 0.89,
    time_horizon_days: 365,
    key_drivers: ['Edge Computing Pioneer', 'Expanding Security Services', 'Large Network Effect'],
    risk_flags: ['Premium Valuation', 'Infrastructure Reliability'],
    risk_level: 'Medium',
    market: 'NYSE',
    sector: 'Technology',
    last_updated: today,
  },
  {
    rank: 14,
    ticker: 'OKTA',
    name: 'Okta, Inc.',
    predicted_multiplier: 2.6,
    confidence: 0.82,
    time_horizon_days: 540,
    key_drivers: ['Leader in Identity Management', 'Acquisition of Auth0', 'Zero Trust Security Trend'],
    risk_flags: ['Security Breaches', 'Integration Challenges'],
    risk_level: 'High',
    market: 'NASDAQ',
    sector: 'Technology',
    last_updated: today,
  },
  {
    rank: 15,
    ticker: 'SOFI',
    name: 'SoFi Technologies',
    predicted_multiplier: 5.5,
    confidence: 0.72,
    time_horizon_days: 730,
    key_drivers: ['Digital Banking Disruption', 'Strong Member Growth', 'Financial Services Ecosystem'],
    risk_flags: ['Path to Profitability', 'Regulatory Environment'],
    risk_level: 'High',
    market: 'NASDAQ',
    sector: 'Financial Services',
    last_updated: today,
  },
  {
    rank: 16,
    ticker: 'PYPL',
    name: 'PayPal Holdings, Inc.',
    predicted_multiplier: 2.1,
    confidence: 0.91,
    time_horizon_days: 365,
    key_drivers: ['Strong Brand in Digital Payments', 'Venmo Monetization', 'Turnaround Potential'],
    risk_flags: ['Increased Competition', 'Slowing Growth'],
    risk_level: 'Low',
    market: 'NASDAQ',
    sector: 'Financial Services',
    last_updated: today,
  },
  {
    rank: 17,
    ticker: 'SQ',
    name: 'Block, Inc.',
    predicted_multiplier: 2.9,
    confidence: 0.80,
    time_horizon_days: 540,
    key_drivers: ['Cash App Ecosystem', 'Seller Business Growth', 'Bitcoin Strategy'],
    risk_flags: ['Volatility from Crypto', 'Economic Sensitivity'],
    risk_level: 'High',
    market: 'NYSE',
    sector: 'Financial Services',
    last_updated: today,
  },
  {
    rank: 18,
    ticker: 'ZM',
    name: 'Zoom Video Communications',
    predicted_multiplier: 2.4,
    confidence: 0.85,
    time_horizon_days: 730,
    key_drivers: ['Enterprise Adoption', 'Product Expansion (Phone, Contact Center)', 'Hybrid Work Trend'],
    risk_flags: ['Post-Pandemic Slowdown', 'Competition from Microsoft Teams'],
    risk_level: 'Medium',
    market: 'NASDAQ',
    sector: 'Technology',
    last_updated: today,
  },
  {
    rank: 19,
    ticker: 'DOCN',
    name: 'DigitalOcean Holdings',
    predicted_multiplier: 4.0,
    confidence: 0.77,
    time_horizon_days: 365,
    key_drivers: ['Focus on SMBs and Developers', 'Simplicity and Predictable Pricing', 'Community Engagement'],
    risk_flags: ['Competition from Hyperscalers', 'Niche Market Focus'],
    risk_level: 'Medium',
    market: 'NYSE',
    sector: 'Technology',
    last_updated: today,
  },
  {
    rank: 20,
    ticker: 'ASAN',
    name: 'Asana, Inc.',
    predicted_multiplier: 3.6,
    confidence: 0.79,
    time_horizon_days: 730,
    key_drivers: ['Work Management Platform Growth', 'Large Enterprise Deals', 'Product Innovation'],
    risk_flags: ['Highly Competitive Space', 'Stock-Based Compensation'],
    risk_level: 'High',
    market: 'NYSE',
    sector: 'Technology',
    last_updated: today,
  }
];


export const mockBacktestData: { [key: string]: BacktestEntry[] } = {
  'NVDA': [
    { ticker: 'NVDA', entry_date: '2022-01-15', exit_date: '2022-07-15', multiplier: 1.8 },
    { ticker: 'NVDA', entry_date: '2022-08-01', exit_date: '2023-02-01', multiplier: 2.5 },
  ],
  'TSLA': [
    { ticker: 'TSLA', entry_date: '2021-11-10', exit_date: '2022-05-10', multiplier: 1.5 },
    { ticker: 'TSLA', entry_date: '2022-06-20', exit_date: '2022-12-20', multiplier: 2.1 },
  ]
};

export const mockPriceData = Array.from({ length: 30 }, (_, i) => ({
  date: `Day ${i + 1}`,
  price: 100 + Math.random() * 20 * Math.sin(i / 3) + i * 2,
}));

export const mockFeatureAttributionData = [
    { name: 'P/E Ratio', value: 0.15, fill: '#8884d8' },
    { name: 'RSI (14)', value: 0.25, fill: '#82ca9d' },
    { name: 'News Sentiment', value: 0.35, fill: '#ffc658' },
    { name: 'Insider Buying', value: 0.10, fill: '#ff8042' },
    { name: 'Volume Spike', value: 0.15, fill: '#00C49F' },
];
